name: Add HW

on:
  workflow_dispatch:
    inputs: 
      user: 
        type: string
        required: true
      variable:
        type: string
        required: true

concurrency:
  group: "add-hello-world-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  add-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a temporary branch
        run: |
          git checkout -b temp-branch-${{ github.run_id }}

      - name: Add "Hello World" to map.py
        run: |
          echo '# Added by run #${{ github.run_id }}' >> map.py
          echo '${{ inputs.variable }}' >> map.py

      - name: Configure Git user
        run: |
          git config --local user.name saquibansari59
          git config --local user.email saquibansari59@gmail.com

      - name: Check Changes
        run: git status

      - name: Check diff
        id: diff_check
        run: |
          if git diff --quiet map.py; then
            echo "diff=no" >> $GITHUB_ENV
          else
            echo "diff=yes" >> $GITHUB_ENV
          fi

      - name: Stage map.py file
        run: git add map.py

      - name: Commit changed file
        if: env.diff == 'yes'
        run: git commit -m "Added Hello World script" --no-verify

      - name: Fetch latest changes from remote
        run: git fetch origin main

      - name: Rebase latest changes onto temporary branch
        run: |
          if ! git rebase origin/main; then
            echo "Rebase failed due to conflicts. Please resolve it manually."
            exit 1
          fi

      - name: Push Changes to main
        if: env.diff == 'yes'
        run: |
          git checkout main
          git merge temp-branch-${{ github.run_id }}
          git push origin main

      - name: Clean up temporary branch
        if: env.diff == 'yes'
        run: git branch -d temp-branch-${{ github.run_id }}
