name: Add_HW

on:
  workflow_dispatch:
    inputs: 
      user: 
        type: string
        required: true
      variable:
        type: string
        required: true

concurrency:
  group: "Add_HW-${{ github.ref }}"  # Ensures jobs with this group name run one at a time per ref (e.g., branch)
  cancel-in-progress: true  # Wait for the previous job to complete instead of canceling it

jobs:
  Add_HW:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add "Hello World" to map.py
        run: |
          echo '${{ inputs.variable }}' >> map.py

      - name: Configure Git user
        run: |
          git config --local user.name saquibansari59
          git config --local user.email saquibansari59@gmail.com

      - name: Check Changes
        run: git status

      - name: Check diff
        id: diff_check
        run: |
          if git diff map.py; then
            echo "diff=yes" >> $GITHUB_ENV
          else
            echo "diff=no" >> $GITHUB_ENV
          fi

      - name: Stage map.py file
        run: git add map.py

      - name: Commit changed file
        if: env.diff == 'yes'
        run: git commit -m "Added Hello World script" --no-verify

      - name: Fetch latest changes from remote
        run: git fetch https://github.com/Saquibansari59/2nd-Project-MAP-.git

      - name: Pull latest changes with rebase
        run: git pull https://github.com/Saquibansari59/2nd-Project-MAP-.git

      - name: Push Changes to main
        if: env.diff == 'yes'
        run: git push https://github.com/Saquibansari59/2nd-Project-MAP-.git
