name: Add HW (separate branch, git merge)

on:
  workflow_dispatch:
    inputs:
      user:
        type: string
        required: true
      variable:
        type: string
        required: true

concurrency:
  group: "add-hello-world-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  add-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout a new branch for script
        run: git checkout -b add-hello-world

      - name: Add "Hello World" to map.py
        run: |
          echo '${{ inputs.variable }}' >> map.py

      - name: Configure Git user
        run: |
          git config --local user.name saquibansari59
          git config --local user.email saquibansari59@gmail.com

      - name: Stage map.py file
        run: git add map.py

      - name: Commit changed file
        run: git commit -m "Added Hello World script" --no-verify

      - name: Fetch latest changes from remote
        run: git fetch https://github.com/Saquibansari59/2nd-Project-MAP-.git

      - name: Merge latest changes
        run: git merge origin/add-hello-world

      - name: Push changes to new branch
        run: git push origin add-hello-world
